CREATE OR REPLACE PROCEDURE PROC_DELETAR_PEDIDO(  P_CD_PEDIDO IN TABELA_PEDIDO.CD_PEDIDO%TYPE )
AS

BEGIN

DELETE FROM TABELA_PEDIDO
  WHERE CD_PEDIDO = P_CD_PEDIDO;
          
    DBMS_OUTPUT.PUT_LINE( 'Alteração realizada com sucesso!' );
    
--EXCEPTION
   -- DBMS_OUTPUT.PUT_LINE( 'Erro na Alteração!' );
 
END PROC_DELETAR_PEDIDO;
