CREATE OR REPLACE PROCEDURE PROC_ATUALIZA_PRECO(P_CD_PRODUTO IN TABELA_PRODUTO.CD_PRODUTO%TYPE)
IS

V_RESULTADO TABELA_PRODUTO.VL_PRECO%TYPE;
T_PRODUTO   TABELA_PRODUTO.VL_PRECO%TYPE;

BEGIN

  SELECT VL_PRECO
  into T_PRODUTO
  FROM tabela_produto
  where cd_produto = P_CD_PRODUTO;
  
    V_RESULTADO:= T_PRODUTO + ( T_PRODUTO * 0.10 );
  
    UPDATE TABELA_PRODUTO
      SET VL_PRECO = V_RESULTADO
      WHERE CD_PRODUTO = P_CD_PRODUTO;
  
END PROC_ATUALIZA_PRECO;