CREATE OR REPLACE PROCEDURE PROC_ALTERAR_PEDIDO(  P_CD_PEDIDO IN TABELA_PEDIDO.CD_PEDIDO%TYPE 
                                                 ,P_DS_PEDIDO IN TABELA_PEDIDO.DS_PEDIDO%TYPE )
AS

BEGIN

UPDATE TABELA_PEDIDO
  SET DS_PEDIDO = P_DS_PEDIDO
  WHERE CD_PEDIDO = P_CD_PEDIDO;
          
    DBMS_OUTPUT.PUT_LINE( 'Alteração realizada com sucesso!' );
    
--EXCEPTION
   -- DBMS_OUTPUT.PUT_LINE( 'Erro na Alteração!' );
 
END PROC_ALTERAR_PEDIDO;
