CREATE TABLE TABELA_CLIENTE
(
    CD_CLIENTE  INTEGER  NOT NULL  ,
    NM_CLIENTE  VARCHAR(50)  ,
    NU_CPF_CNPJ INTEGER  ,
    TP_CLIENTE  VARCHAR(20) ,
    CONSTRAINT CONS_TABELA_CLIENTE  PRIMARY KEY (CD_CLIENTE) ENABLE /*chave primaria da tabela de Cliente*/
);


