CREATE TABLE TABELA_PRODUTO
(
    CD_PRODUTO  INTEGER NOT NULL,
    DS_PRODUTO  VARCHAR(50)  ,
    VL_PRECO    DECIMAL(3,2)  ,
    QTD_SALDO   INTEGER ,
    CONSTRAINT CONS_TABELA_PRODUTO  PRIMARY KEY (CD_PRODUTO) ENABLE /*chave primaria da tabela de PRODUTO*/
);
