CREATE TABLE TABELA_PEDIDO
(
    CD_PEDIDO            INTEGER NOT NULL ,
    VENDEDOR_CD_VENDEDOR INTEGER NOT NULL , /* */
    CLIENTE_CD_CLIENTE   INTEGER NOT NULL , /* */
    
    DS_PEDIDO            VARCHAR(50)  ,
    VL_TOTAL             DECIMAL(4,2) NOT NULL ,
    DT_PEDIDO            DATE         NOT NULL ,
    TP_PEDIDO            VARCHAR(20)  NOT NULL ,
    
    CONSTRAINT PK_TABELA_PEDIDO    PRIMARY KEY (CD_PEDIDO) ENABLE , /*chave primaria da tabela de Cliente*/
    CONSTRAINT FK_TABELA_VENDEDOR  FOREIGN KEY (VENDEDOR_CD_VENDEDOR) REFERENCES TABELA_VENDEDOR(CD_VENDEDOR),
    CONSTRAINT FK_TABELA_CLIENTE   FOREIGN KEY (CLIENTE_CD_CLIENTE)   REFERENCES TABELA_CLIENTE(CD_CLIENTE)/*REFERENCES-> tabela de onde vem(nome do campo dela)*/
);

CREATE INDEX TABELA_PEDIDO_FK_INDEX1 ON TABELA_PEDIDO(CLIENTE_CD_CLIENTE);

CREATE INDEX TABELAPEDIDO_FK_INDEX2  ON TABELA_PEDIDO(VENDEDOR_CD_VENDEDOR);