CREATE TABLE TABELA_VENDEDOR
(
    CD_VENDEDOR  INTEGER  NOT NULL  ,
    NM_VENDEDOR  VARCHAR(5)  ,
    NU_CPF       INTEGER  ,
    DS_ENDERRECO VARCHAR(50) ,
    /* DS_ENDERRECO VARCHAR2(50) ,*/
    CONSTRAINT CONS__TABELA_VENDEDOR  PRIMARY KEY (CD_VENDEDOR) ENABLE /*chave primaria da tabela de Cliente*/
/*  CONSTRAINT CONS_VENDEDOR_NU_CPF  (nu_cpf) UNIQUE /*UNIQUE-> diz que é um numero unico**/
);
