CREATE TABLE TABELA_ITEM_PEDIDO
(
    CD_ITEM_PEDIDO     INTEGER NOT NULL ,
    PRODUTO_CD_PRODUTO INTEGER NOT NULL , /* */
    PEDIDO_CD_PEDIDO   INTEGER NOT NULL , /* */
    
    QT_ITEM            INTEGER  ,
    VL_UNIT            Float(6),
    VL_TOTAL           Float(6) ,
    
    CONSTRAINT PK_TABELA_ITEM_PEDIDO  PRIMARY KEY (CD_ITEM_PEDIDO) ENABLE , /*chave primaria da tabela de Cliente*/
    CONSTRAINT FK_TABELA_PRODUTO      FOREIGN KEY (PRODUTO_CD_PRODUTO) REFERENCES TABELA_PRODUTO(CD_PRODUTO),
    CONSTRAINT FK_TABELA_PEDIDO       FOREIGN KEY (PEDIDO_CD_PEDIDO)   REFERENCES TABELA_PEDIDO(CD_PEDIDO)
);


CREATE INDEX TABELA_ITEM_PEDIDO_FK_INDEX1 ON TABELA_ITEM_PEDIDO (PRODUTO_CD_PRODUTO);

CREATE INDEX TABELA_ITEM_PEDIDO_FK_INDEX2 ON TABELA_ITEM_PEDIDO (PEDIDO_CD_PEDIDO);