CREATE OR REPLACE TRIGGER TRI_PEDIDO
  BEFORE
    INSERT ON TABELA_PEDIDO for EACH ROW

BEGIN

IF (:NEW.VL_TOTAL > 100000 )THEN
  RAISE_APPLICATION_ERROR(-20205,'VALOR ESTA SENDO EXCEDIDO DO VALOR MAXIMO DE 100.000,00!!');

END IF;


END TRI_PEDIDO;