CREATE OR REPLACE FUNCTION CONSULTAR_PEDIDO(P_CD_PEDIDO IN TABELA_PEDIDO.CD_PEDIDO%TYPE)
RETURN TABELA_PEDIDO%ROWTYPE
AS
V_PEDIDO TABELA_PEDIDO%ROWTYPE;
BEGIN

SELECT * 
INTO V_PEDIDO
  FROM TABELA_PEDIDO
  WHERE CD_PEDIDO = P_CD_PEDIDO;

END CONSULTAR_PEDIDO;